# Generated by Django 2.2.4 on 2019-08-21 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190821_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='code',
            new_name='postal_code',
        ),
    ]
