# Generated by Django 2.2.4 on 2019-08-21 12:08

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190821_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pickup_location',
        ),
        migrations.AlterField(
            model_name='address',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(2.349014, 48.864716), srid=4326),
        ),
    ]
