# Generated by Django 2.2.4 on 2019-08-21 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_productorprofile_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ProductorProfile'),
        ),
    ]
