# Generated by Django 2.2.4 on 2019-08-23 08:01

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190823_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorprofile',
            name='pictures',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.FileField(upload_to=''), default=list, size=None),
        ),
    ]
