# Generated by Django 2.2.4 on 2019-09-10 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20190823_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='saved_products',
            field=models.ManyToManyField(blank=True, related_name='saved_products', to='core.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.ProductorProfile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='shopping_history',
            field=models.ManyToManyField(blank=True, related_name='shopping_history', to='core.Product'),
        ),
    ]
