# Generated by Django 2.2.5 on 2019-09-11 10:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20190910_0823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('checked_out', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_pickup',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='shopping_history',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('BAKERY', 'bakery'), ('ALCOOL', 'alcool'), ('MEAT', 'meat'), ('VEGETABLE', 'vegetable')], default='MEAT', max_length=120),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='saved_products',
            field=models.ManyToManyField(blank=True, to='core.Product'),
        ),
        migrations.CreateModel(
            name='DeliveryMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('modality', models.TextField(default='')),
                ('delay', models.IntegerField(default=2)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Address')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_delivery_modes', to='core.ProductorProfile')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.Cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Product')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='core.UserProfile'),
        ),
    ]
