# Generated by Django 2.2.5 on 2019-09-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20190913_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='saved_products',
            field=models.ManyToManyField(blank=True, related_name='fans', to='core.Product'),
        ),
    ]
