# Generated by Django 2.2.4 on 2019-08-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20190819_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mail_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
