# Generated by Django 2.2.4 on 2019-08-21 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20190820_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productor_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
