# Generated by Django 2.2.4 on 2019-08-21 09:10

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_product_exploitation'),
        ('authentication', '0006_auto_20190821_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorprofile',
            name='exploitation',
        ),
        migrations.AddField(
            model_name='productorprofile',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Address'),
        ),
        migrations.AddField(
            model_name='productorprofile',
            name='pictures',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(upload_to=''), blank=True, null=True, size=None),
        ),
    ]
