# Generated by Django 2.2.4 on 2019-08-21 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20190821_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='shopping_history',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='ProductorProfile',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
